version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: authify-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=authify_db
      - MYSQL_ROOT_PASSWORD=vrunda1603
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: authify-redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: authify-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/authify_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=vrunda1603
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=UVdFUlRZVUlPUEFTREZHSEpLTFpYQ1ZCTk0xMjM0NTY3ODkwYWJjZGVmQUJDREVGR0g=
      - SPRING_MAIL_USERNAME=jateendhaduk456@gmail.com
      - SPRING_MAIL_PASSWORD=juka rgou okbk qbjv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: authify-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
