spring.application.name=Authify 
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authify_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vrunda1603}
spring.jpa.hibernate.ddl-auto=update
# jwt token
jwt.secret=${JWT_SECRET:UVdFUlRZVUlPUEFTREZHSEpLTFpYQ1ZCTk0xMjM0NTY3ODkwYWJjZGVmQUJDREVGR0g=}
jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP expiry in minutes
app.otp.expiry-minutes=10

# redis config
spring.data.redis.host=${SPRING_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}
spring.data.redis.ssl=${SPRING_REDIS_SSL:false}
